export type AppLocale = 'es' | 'en';

export const uiStrings = {
  es: {
    loading: 'Cargando...',
    loadError: 'No se pudo cargar la información del portafolio.',
    unknownError: 'Error desconocido',
    aboutIndex: '01 — Sobre mí',
    skillsIndex: '03 — Habilidades',
    visorDocLabel: 'Documento',
    visorCredLabel: 'Credencial verificada',
    themeToLight: 'Activar modo claro',
    themeToDark: 'Activar modo oscuro',
    langEs: 'Español',
    langEn: 'English',
    langSwitch: 'Cambiar idioma',
    navLabel: 'Navegación principal',
    featured: 'Destacado',
    stack: 'Stack',
    moreProjects: 'Más proyectos en camino',
    carouselHint: 'Pasa el cursor sobre una tarjeta para pausar y explorar',
    institutionalProject: 'Proyecto institucional · producción',
    certCategories: {
      tecnologia: 'Tecnología',
      metodologias: 'Metodologías',
      cloud: 'Cloud',
      idiomas: 'Idiomas',
      otros: 'Otros',
    },
    certSectionSubtitle: (total: number, verifiable: number) =>
      `${total} certificaciones activas · ${verifiable} verificables desde el navegador.`,
    certFeaturedHeading: 'Credenciales y documentos',
    certIndex: '04 — Certificaciones',
    viewDocument: 'Ver documento',
    download: 'Descargar',
    viewDiploma: 'Ver diploma',
    viewCredential: 'Ver credencial',
    openExternal: 'Abrir ↗',
    showMoreCerts: (n: number) => `Ver las ${n} certificaciones restantes`,
    pdfBadge: 'PDF',
    onlineBadge: 'En línea',
    contactIndex: '05 — Contacto',
    downloadCv: 'Descargar CV',
    projectsIndex: (n: number) => `0${n} — Proyectos`,
    visorDocument: 'Visor de documento',
    visorCredential: 'Credencial verificada',
    openInTab: 'Abrir en pestaña ↗',
    close: 'Cerrar',
    closeVisor: 'Cerrar visor',
    iframeHint: 'Si no carga, usa «Abrir en pestaña».',
    mobilePdfTitle: 'En este dispositivo el visor embebido no está disponible',
    mobilePdfBody:
      'Safari y muchos navegadores móviles no muestran PDFs dentro de la página. Abre el documento en una pestaña nueva o descárgalo.',
    viewDocBtn: 'Ver documento',
    downloadPdf: 'Descargar PDF',
    available: 'Disponible para proyectos',
    scrollHint: 'Scroll',
  },
  en: {
    loading: 'Loading...',
    loadError: 'Could not load portfolio data.',
    unknownError: 'Unknown error',
    aboutIndex: '01 — About',
    skillsIndex: '03 — Skills',
    visorDocLabel: 'Document',
    visorCredLabel: 'Verified credential',
    themeToLight: 'Switch to light mode',
    themeToDark: 'Switch to dark mode',
    langEs: 'Español',
    langEn: 'English',
    langSwitch: 'Change language',
    navLabel: 'Main navigation',
    featured: 'Featured',
    stack: 'Stack',
    moreProjects: 'More projects coming soon',
    carouselHint: 'Hover a card to pause and explore',
    institutionalProject: 'Institutional project · production',
    certCategories: {
      tecnologia: 'Technology',
      metodologias: 'Methodologies',
      cloud: 'Cloud',
      idiomas: 'Languages',
      otros: 'Other',
    },
    certSectionSubtitle: (total: number, verifiable: number) =>
      `${total} active certifications · ${verifiable} verifiable in the browser.`,
    certFeaturedHeading: 'Credentials & documents',
    certIndex: '04 — Certifications',
    viewDocument: 'View document',
    download: 'Download',
    viewDiploma: 'View diploma',
    viewCredential: 'View credential',
    openExternal: 'Open ↗',
    showMoreCerts: (n: number) => `Show ${n} more certifications`,
    pdfBadge: 'PDF',
    onlineBadge: 'Online',
    contactIndex: '05 — Contact',
    downloadCv: 'Download résumé',
    projectsIndex: (n: number) => `0${n} — Projects`,
    visorDocument: 'Document viewer',
    visorCredential: 'Verified credential',
    openInTab: 'Open in new tab ↗',
    close: 'Close',
    closeVisor: 'Close viewer',
    iframeHint: 'If it does not load, use «Open in new tab».',
    mobilePdfTitle: 'Embedded viewer is not available on this device',
    mobilePdfBody:
      'Safari and many mobile browsers cannot display PDFs inline. Open the document in a new tab or download it.',
    viewDocBtn: 'View document',
    downloadPdf: 'Download PDF',
    available: 'Open to opportunities',
    scrollHint: 'Scroll',
  },
} as const;

export type UiStrings = (typeof uiStrings)[AppLocale];
